### ISSUE TITLE
apply go fmt

### ISSUE THREAD

**Issue by davidalpert** [deepgram-devs/deepgram-go-sdk#10]
## Proposed changes

I propose that we `go fmt` the code to increase formatting consistency, increase readability, and reduce whitespace noise in hactoberfest and future contributions. 

## Context

The golang community tends to align around the `gofmt` tool to provide consistent formatting for Go source code. (see: [go fmt your code](https://go.dev/blog/gofmt) on [The Go Blog](https://go.dev/blog/))

## Possible Implementation

`go fmt` could be run against the code on the `main` branch

this would possibly cause merge conflicts with any open PRs 

## Other information

while running this once on `main` would address formatting today, it would be a good idea to bake this into the development/contribution workflow, either through build scripts (e.g. `Makefile`s are pretty common in Go repos) or github actions in a PR workflow (e.g. this [gofmt-action](https://github.com/Jerome1337/gofmt-action) action seems to run `gofmt` and fail a PR if it detects any changes) or even suggesting a pre-commit hook script (see: e.g. [this example](https://gist.github.com/liues1992/66c5a1f865085f90dd49038693e39a95))

**Comment by jpvajda** [comment]
closing as #13 seemed to resolve this.
