### ISSUE TITLE
organize `deepgram` package files into a single folder

### ISSUE THREAD

**Issue by davidalpert** [deepgram-devs/deepgram-go-sdk#11]
## Proposed changes

I propose reorganizing `deepgram` package source files into a single folder.

## Context

It is unusual to the point of non-idiomatic to have Go source files from different folders.

In the [current HEAD commit](https://github.com/deepgram-devs/deepgram-go-sdk/tree/19776bff12ff6c576e6719953d35943e5d020404) we have the `deepgram` package used in two different folders:
1. at the root: [`./deepgram.go`](https://github.com/deepgram-devs/deepgram-go-sdk/blob/19776bff12ff6c576e6719953d35943e5d020404/deepgram.go#L1); and
2. inside the `types` folder: [`./types/prerecorded.go`](https://github.com/deepgram-devs/deepgram-go-sdk/blob/main/types/prerecorded.go#L1)

## Possible Implementation

I suggest refactoring the `deepgram` package source files into a single folder, either at the root (which is common for library repos) or into a source folder (e.g. `./deepgram`) which is also common for Go packages, to collect source code for a package into a folder named for that package.

At this point I would suggest moving `./types/prerecorded.go` into the root which still requires importing with an alias:

```go
import (
	deepgram "github.com/deepgram-devs/go-sdk"
)
```

The other approach, to move all the `deepgram` package files into a new folder `./deepgram` would allow importing like this:

```go
import (
    "github.com/deepgram-devs/go-sdk/deepgram"
)
```

A third option might be to organize the code into multiple packages named for related concerns, if you have multiple related concerns, like `transcriptions`, `invitations`, etc, but with only a few files a single package is probably sufficient.

**Comment by jpvajda** [comment]
Closing as this seems to be resolved by #15
