### ISSUE TITLE
Add topic detection feature

### ISSUE THREAD

**Issue by MichaelJolley** [deepgram-devs/deepgram-go-sdk#17]
## Proposed changes

- Support calling our Topic Detection Feature with Go SDK.
- Developers can utilize Topic Detection feature with detect_topics=true query parameter
- Update any usage requests that allow filtering by feature to include detect_topics

## Context

Allow customers to identify and detect topics in their transcript.

## Other information

- Sample URL - https://api.beta.deepgram.com/v1/listen?detect_topics=true
  - Engineering Doc - `detect_topics`: string indicating which version of the topic detection model to use. Setting this variable turns topic detection on.

## Sample Output 

`topics`: An optional array of the topics recognized in the audio. The array will be sorted by the start_word attribute, ascending.

![Screen Shot 2022-09-07 at 3 35 24 PM](https://user-images.githubusercontent.com/1228996/198089010-6a89a4f2-8593-4b56-8e54-3ab25927df5e.png)

**Comment by briancbarrow** [comment]
closed with #29
