### ISSUE TITLE
Add language detection feature

### ISSUE THREAD

**Issue by MichaelJolley** [deepgram-devs/deepgram-go-sdk#22]
## Proposed changes

- Support calling our Language Detection Parameter 
- Developers can utilize language detection with detect_language=true parameter.
- Update usage requests that allow filtering by feature

## Context

Allow customers to detect language in their transcript and route it to the detected language model.

## Other information

- Sample URL - https://api.beta.deepgram.com/v1/listen?detect_language=true
- Documentation lives at https://developers.deepgram.com/documentation/features/detect-language/

## Sample Output 

```js
 "alternatives": [
   {
     "transcript": "c'est une bonne situation ça mais savez je crois pas qu'il y ait de bonnes ou une mauvaises situation si devais résumer ma vie aujourd'hui avec vous je dirais que c'est des rencontres des gens qui ont tendu la main peut-être à un moment où je ne pouvais pas où ....",
     "confidence": 0.9323341,
     "words": [
       ...
     ]
   }
 ],
 "detected_language": "fr" 
```

**Comment by briancbarrow** [comment]
closed with #29
