### ISSUE TITLE
SecondsToTimestamp format padding issue

### ISSUE THREAD

**Issue by NickBeukema** [deepgram-devs/deepgram-go-sdk#27]
## What is the current behavior?

When generating VTT files from utterances, the timestamps are incorrectly formatted for anything under 10 seconds. Here's a snippet of the most recent VTT I've generated:

```
1
00:00:1.814 --> 00:00:5.423
Test one, two, three. I'm testing transcripts

2
00:00:6.318 --> 00:00:8.333
to see that they come through accurately
```

## Steps to reproduce

Calling `ToWebVTT` on a `PreRecordedResponse`.

## Expected behavior

As you can see in the example above, the first timestamp is: `00:00:1.814`, and should be `00:00:01.814` according to the [WebVTT Spec](https://www.w3.org/TR/webvtt1/#webvtt-timestamp):

> 4. Two [ASCII digits](https://www.w3.org/TR/html51/infrastructure.html#ascii-digits), representing the seconds as a base ten integer in the range 0 ≤ seconds ≤ 59.

## Please tell us about your environment
  
- **Operating System/Version:** Macos Ventura, M1
- **Language:** Go v1.18 and v1.20
- **Browser:** N/A

## Other information

I'll link up my PR for the proposed fix, Go's float formatting requires you specify the _total_ number of digits as the first number (including the decimal point) and the decimal precision as the second number:

```
return fmt.Sprintf("%02d:%02d:%02.3f", hours, minutes, seconds)
```

Should be:

```
return fmt.Sprintf("%02d:%02d:%06.3f", hours, minutes, seconds)
```

**Comment by briancbarrow** [comment]
Thanks @NickBeukema I approved and merged your PR.
