### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by pablodz** [deepgram-devs/deepgram-go-sdk#31]
https://github.com/deepgram-devs/deepgram-go-sdk/blob/ce4daa0a5fb4120a03cc7bf171f59fae188cc32e/go.mod#L1

rename to github.com/deepgram-devs/deepgram-go-sdk to avoid:

![image](https://user-images.githubusercontent.com/28235457/231008558-348e02de-9ee1-4637-a80b-e80659b0f5c1.png)

**Comment by lukeocodes** [comment]
hey @pablodz would you like to make a PR for this?
