### ISSUE TITLE
Can't handle errors with LiveTranscription

### ISSUE THREAD

**Issue by cchunn-veritone** [deepgram-devs/deepgram-go-sdk#35]
## What is the current behavior?

Currently, the `LiveTranscription` function claims it returns errors, but then a call to `log.Fatal` inside the code ends execution before the return can ever happen.

## Steps to reproduce

Connect with options that cause an error (Like `language: en-NZ` + `model: meeting`

## Expected behavior

I expect the error to be returned by the function, so I can handle it in scope.

**Comment by cchunn-veritone** [comment]
This is an easy enough fix:

Current Function:
```golang
func (dg *Client) LiveTranscription(options LiveTranscriptionOptions) (*websocket.Conn, *http.Response, error) {
	query, _ := query.Values(options)
	u := url.URL{Scheme: "wss", Host: dg.Host, Path: "/v1/listen", RawQuery: query.Encode()}
	log.Printf("connecting to %s", u.String())

	header := http.Header{
		"Host":          []string{dg.Host},
		"Authorization": []string{"token " + dg.ApiKey},
		"X-DG-Agent":    []string{dgAgent},
	}

	c, resp, err := websocket.DefaultDialer.Dial(u.String(), header)

	if err != nil {
		log.Printf("handshake failed with status %s", resp.Status)
		log.Fatal("dial:", err)
	}
	return c, resp, nil
}
```

Fixed Function:
```golang
func (dg *Client) LiveTranscription(options LiveTranscriptionOptions) (*websocket.Conn, *http.Response, error) {
	query, _ := query.Values(options)
	u := url.URL{Scheme: "wss", Host: dg.Host, Path: "/v1/listen", RawQuery: query.Encode()}
	log.Printf("connecting to %s", u.String())

	header := http.Header{
		"Host":          []string{dg.Host},
		"Authorization": []string{"token " + dg.ApiKey},
		"X-DG-Agent":    []string{dgAgent},
	}

	return  websocket.DefaultDialer.Dial(u.String(), header)
}
```

**Comment by SandraRodgers** [comment]
[cchunn-veritone](https://github.com/cchunn-veritone), would you like to make a PR to fix this?

**Comment by jpvajda** [comment]
@dvonthenen 👋  I'm curious if you'll be handling this issue in our upcoming V1 Major Release of the GoSDK?

**Comment by dvonthenen** [comment]
This should be fixed in this PR:
https://github.com/deepgram-devs/deepgram-go-sdk/pull/88

**Comment by dvonthenen** [comment]
Addressed in PR https://github.com/deepgram-devs/deepgram-go-sdk/pull/108. Closing because PR was merged.
