### ISSUE TITLE
Support options in Redact

### ISSUE THREAD

**Issue by Weimw** [deepgram-devs/deepgram-go-sdk#53]
## Proposed changes
- Support other redact options (e.g. `pci`, `ssn`, `numbers`)
- Support multiple instances in query string (e.g., `redact=pci&redact=numbers`)

## Context

Current redact options only supports true and false, while API Docs provides options for `pci`, `ssn` and `numbers`

## Other information

Docs for redaction: https://developers.deepgram.com/docs/redaction

**Comment by SandraRodgers** [comment]
See also https://developers.deepgram.com/reference/pre-recorded

**Comment by jpvajda** [comment]
This will be considering a major breaking change so we'll consider this in our 1.0 release in the future.

**Comment by jpvajda** [comment]
@dvonthenen 👋  I'm curious what your thoughts are on this issue?

**Comment by dvonthenen** [comment]
Will take a look

**Comment by dvonthenen** [comment]
Addressed in PR https://github.com/deepgram-devs/deepgram-go-sdk/pull/113. Merged. Closing.
